import { z } from "zod";
import { JsonValueSchema } from "./schemas/common.js";

export const ProtocolErrorCode = {
  INVALID_REQUEST: "INVALID_REQUEST",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",
  RATE_LIMITED: "RATE_LIMITED",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  BRIDGE_DISCONNECTED: "BRIDGE_DISCONNECTED",
  BRIDGE_TIMEOUT: "BRIDGE_TIMEOUT",
  REQUEST_TIMEOUT: "REQUEST_TIMEOUT",
  BRIDGE_PROTOCOL_ERROR: "BRIDGE_PROTOCOL_ERROR",
  WORLD_MISMATCH: "WORLD_MISMATCH",
  UNSUPPORTED_FOUNDRY_VERSION: "UNSUPPORTED_FOUNDRY_VERSION",
  UNSUPPORTED_SYSTEM: "UNSUPPORTED_SYSTEM",
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  DOCUMENT_TYPE_UNSUPPORTED: "DOCUMENT_TYPE_UNSUPPORTED",
  DOCUMENT_VALIDATION_FAILED: "DOCUMENT_VALIDATION_FAILED",
  OPERATION_NOT_SUPPORTED: "OPERATION_NOT_SUPPORTED",
  DELETE_CONFIRMATION_INVALID: "DELETE_CONFIRMATION_INVALID",
  DELETE_CONFIRMATION_EXPIRED: "DELETE_CONFIRMATION_EXPIRED",
  DELETE_TARGET_CHANGED: "DELETE_TARGET_CHANGED",
  PLUTONIUM_UNAVAILABLE: "PLUTONIUM_UNAVAILABLE",
  PLUTONIUM_VERSION_UNSUPPORTED: "PLUTONIUM_VERSION_UNSUPPORTED",
  PLUTONIUM_API_INCOMPATIBLE: "PLUTONIUM_API_INCOMPATIBLE",
  PLUTONIUM_IMPORTER_UNAVAILABLE: "PLUTONIUM_IMPORTER_UNAVAILABLE",
  PLUTONIUM_REFERENCE_UNSUPPORTED: "PLUTONIUM_REFERENCE_UNSUPPORTED",
  PLUTONIUM_SOURCE_NOT_FOUND: "PLUTONIUM_SOURCE_NOT_FOUND",
  PLUTONIUM_INTERACTIVE_ONLY: "PLUTONIUM_INTERACTIVE_ONLY",
  PLUTONIUM_IMPORT_FAILED: "PLUTONIUM_IMPORT_FAILED",
  PLUTONIUM_IMPORT_TIMEOUT: "PLUTONIUM_IMPORT_TIMEOUT",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export const ProtocolErrorCodeSchema = z.enum(ProtocolErrorCode);
export type ProtocolErrorCodeValue = z.infer<typeof ProtocolErrorCodeSchema>;

export const ProtocolErrorSchema = z
  .object({
    code: ProtocolErrorCodeSchema,
    message: z.string().min(1).max(2048),
    details: JsonValueSchema.optional()
  })
  .strict();

export type ProtocolError = z.infer<typeof ProtocolErrorSchema>;
